### ISSUE TITLE
想请教一下 infer 文件里面的 config 变量具体是什么值呢？

### ISSUE THREAD

**Issue by drockser** [HaozheZhao/MIC#1]
可否给一个完整的infer 呢？

**Comment by HaozheZhao** [comment]
Sorry, currently the release of my model and data is still in progress, and the maintenance of the repository is not yet complete.
For the config.json file, you can simply use the same file from [instructnlip](https://huggingface.co/Salesforce/instructblip-flan-t5-xxl).
You can use the code from our [repository](https://github.com/HaozheZhao/MIC),
and try to load the model using the following script:
```
from model.instructblip import InstructBlipConfig, InstructBlipModel, InstructBlipPreTrainedModel,InstructBlipForConditionalGeneration,InstructBlipProcessor
import transformers
from PIL import Image
import torch
model_ckpt="BleachNick/MMICL-Instructblip-T5-xxl"
config_ckpt = "Salesforce/instructblip-flan-t5-xxl"
config = InstructBlipConfig.from_pretrained(config_ckpt )
model = InstructBlipForConditionalGeneration.from_pretrained(
        model_ckpt,
        config=config).to('cuda:0') 
```
