### ISSUE TITLE
MME和MMBench上的评测代码

### ISSUE THREAD

**Issue by mine348** [HaozheZhao/MIC#12]
作者你好，请问一下huggingface上的[mmicl模型](https://huggingface.co/BleachNick/MMICL-Instructblip-T5-xxl/tree/main)是否能得出论文中的评测结果呢（[MME](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation) ：Perception=1376, Cognition=360; [MMBench](https://opencompass.org.cn/leaderboard-multimodal)：Overall=65.2）？使用最新版的[MIC](https://github.com/HaozheZhao/MIC)推理代码在尝试了多种prompt之后均未得到理想的评测分数。不知作者可否公开一下评测MME和MMBench的prompt代码

**Comment by HaozheZhao** [comment]
Hi, we use the same prompt as shown in the MME/MMBench dataset form. And for each instance, we will add an image selection declaration as a prefix, like "Use theimage 0: <image>{replace token} as a visual aid to help you answer the questions accurately.". More details of the prompts and inference code for different tasks and benchmarks will be released soon.

**Comment by buptlihang** [comment]
Waiting a infenence code for mme
