### ISSUE TITLE
How to achieve multi-turn conversation

### ISSUE THREAD

**Issue by waltonfuture** [HaozheZhao/MIC#17]
Maybe add the history conversation into the prompt?

**Comment by HaozheZhao** [comment]
While our model wasn't specifically trained for multi-turn conversations, interestingly, during the evaluation phase, we realised that the MMICL exhibits some capability for such dialogue. This likely stems from its inherent aptitude for in-context learning. During our assessment and demonstration, we incorporated prior dialogue into the cue and supplied it to the model to generate new responses.
