### ISSUE TITLE
wiil you release the checkpoint?

### ISSUE THREAD

**Issue by xdhhh** [HaozheZhao/MIC#8]

**Comment by HaozheZhao** [comment]
Hi there, it appears that due to a network problem, the upload of the chkp file failed and we were not aware of it. 
Currently, we are in the process of re-uploading the ckpt file. This may take some time. 
In the meantime, you can try using the xl-version of our MMICL by following this [link](https://huggingface.co/BleachNick/MIC-vit-T5-xl). We published it approximately a month ago.

**Comment by HaozheZhao** [comment]
You can find the MMICL-Instruct-XXL ckpt [here](https://huggingface.co/BleachNick/MMICL-Instructblip-T5-xxl/tree/main).

**Comment by vishaal27** [comment]
Are you also currently uploading the files for this repository: https://huggingface.co/BleachNick/MMICL-Instructblip-T5-xl?

**Comment by HaozheZhao** [comment]
Yeah, we are uploading it. Previously, we didn't notice that the upload failed due to a network issue. Right now, we are attempting to upload the other version of MMICL along with the image data in MIC. The network of Huggingface.co is unstable, and we are putting in our best efforts to enhance the uploading process.
Now you can get the ckpt of instruct-xl verson of MMICL in this [link](https://huggingface.co/BleachNick/MMICL-Instructblip-T5-xl)

**Comment by vishaal27** [comment]
Thanks for the prompt response, I see the checkpoint files for the XL model online now!

**Comment by OuYangg** [comment]
Huggingface is now inaccessible in China, is there another way to download it?

**Comment by HaozheZhao** [comment]
Well, unfortunately, there is nothing we can do about this. The ban on Huggingface is also adversely affecting us. It makes sharing the model and data so much difficult.
Maybe we can provide a Google Drive link? Or do you recommend any other option?

**Comment by xdhhh** [comment]
when i try to use the ckpt you provide and the inference code in README, these is an error 

Error(s) in loading state_dict for InstructBlipForConditionalGeneration:
	size mismatch for qformer.embeddings.word_embeddings.weight: copying a param with shape torch.Size([30623, 768]) from checkpoint, the shape in current model is torch.Size([30523, 768]).

**Comment by HaozheZhao** [comment]
Hi there! It seems there is also a typo. You need to load the model with the config from the model ckp path. It was a mistake in our README. Thank you for pointing it out, and we have fixed it.
As shown as following codes:
a flamingo. They are native to South America and are known for their bright red plumage and distinctive call.
```
# For T5 based model
from model.instructblip import InstructBlipConfig, InstructBlipModel, InstructBlipPreTrainedModel,InstructBlipForConditionalGeneration,InstructBlipProcessor
import datasets
import json
import transformers
from PIL import Image
import torch
model_type="instructblip"
model_ckpt="/home/haozhezhao/MMICL-Instructblip-T5-xxl"
processor_ckpt = "Salesforce/instructblip-flan-t5-xxl"
config = InstructBlipConfig.from_pretrained(model_ckpt )

if 'instructblip' in model_type:
    model = InstructBlipForConditionalGeneration.from_pretrained(
        model_ckpt,
        config=config).to('cuda:0',dtype=torch.bfloat16) 

image_palceholder="图"
sp = [image_palceholder]+[f"<image{i}>" for i in range(20)]
processor = InstructBlipProcessor.from_pretrained(
    processor_ckpt
)
sp = sp+processor.tokenizer.additional_special_tokens[len(sp):]
processor.tokenizer.add_special_tokens({'additional_special_tokens':sp})
if model.qformer.embeddings.word_embeddings.weight.shape[0] != len(processor.qformer_tokenizer):
    model.qformer.resize_token_embeddings(len(processor.qformer_tokenizer))
replace_token="".join(32*[image_palceholder])
replace_token=32*[image_palceholder]

image = Image.open ("images/cal_num1.png")
image1 = Image.open ("images/cal_num2.png")
image2 = Image.open ("images/cal_num3.png")
images = [image,image1,image2]

prompt = [f'Use the image 0: <image0>{replace_token},image 1: <image1>{replace_token} and image 2: <image2>{replace_token} as a visual aid to help you calculate the equation accurately. image 0 is 2+1=3.\nimage 1 is 5+6=11.\nimage 2 is"']
prompt = " ".join(prompt)

inputs = processor(images=images, text=prompt, return_tensors="pt")

inputs['pixel_values'] = inputs['pixel_values'].to(torch.bfloat16)
inputs['img_mask'] = torch.tensor([[1 for i in range(len(images))]])
inputs['pixel_values'] = inputs['pixel_values'].unsqueeze(0)

inputs = inputs.to('cuda:0')
outputs = model.generate(
        pixel_values = inputs['pixel_values'],
        input_ids = inputs['input_ids'],
        attention_mask = inputs['attention_mask'],
        img_mask = inputs['img_mask'],
        do_sample=False,
        max_length=50,
        min_length=1,
        set_min_padding_size =False,
)
generated_text = processor.batch_decode(outputs, skip_special_tokens=True)[0].strip()
print(generated_text)
# output: 3x6=18"

```

**Comment by OuYangg** [comment]
> Well, unfortunately, there is nothing we can do about this. The ban on Huggingface is also adversely affecting us. It makes sharing the model and data so much difficult.
> Maybe we can provide a Google Drive link? Or do you recommend any other option?

I have found a way to download, thx.
